---
- name: Install and configure Apache HTTP Server
  hosts: vm
  become: yes
  tasks:
    - name: Install Apache HTTP Server
      package:
        name: httpd
        state: present
    - name: Create a simple index.html file
      copy:
        content: "<html><body><h1>Hello from Ansible!</h1></body></html>"
        dest: /var/www/html/index.html


  handlers:
    - name: Start httpd server
      ansible.builtin.systemd:
        service: dhcpd
        enabled: true
        state: restarted

    - name: Add http to firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
